apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: project-a
    name: project-a
    group: bro
    version: "%gitTag%"
  name: project-a
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project-a
  template:
    metadata:
      labels:
        app: project-a
        name: project-a
        group: bro
        version: "%gitTag%"
    spec:
      containers:
      - image: "%containerRegistry%/kevintijssen/project-a:%gitTag%"
        name: project-a
