# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push only for the "main" branch
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  checkout:
    name: Checkout all necessary repo's
    # The type of runner that the job will run on
    runs-on: [self-hosted]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:       
      - name: Check out local project repository
        uses: actions/checkout@v3

      - name: Check out global-actions repository
        uses: actions/checkout@v3
        with:
          repository: KTijssen/global-actions
          ref: main
          token: ${{ secrets.PAT_TOKEN }}
          path: "global-actions"

  SetVersion:
    name: Semantic Versioning
    needs: checkout
    runs-on: [self-hosted]
    steps:
      - name: Get version number
        shell: bash
        run: ./global-actions/common.sh