name: Project-A

on:
  push:
    #branches: [ "main" ]
  workflow_dispatch:
    inputs:
      run_e2e_test:
        description: Run E2E tests
        required: true
        type: boolean
        default: false

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkout:
    name: Checkout Project Repo
    runs-on: [self-hosted]
    steps:       
      - name: Checkout project repository
        uses: actions/checkout@v3
      - name: Move yaml files to workflow dir
        shell: bash
        run: |
          ls -la
          mv ./global-actions/.github/workflows/*.yaml ./.github/workflows/
          ls ./.github/workflows/


  # SetVersion:
  #   needs: checkout
  #   name: Common
  #   uses: KTijssen/global-actions/.github/workflows/common.yaml@beta
  #   with:
  #     major: "1"
  #     minor: "0"
  #   secrets: inherit


  # BuildMaven:
  #   name: Build
  #   needs: SetVersion
  #   uses: KTijssen/global-actions/.github/workflows/maven.yaml@beta
  #   secrets: inherit

  # BuildManifests:
  #   name: Build
  #   needs: SetVersion
  #   uses: KTijssen/global-actions/.github/workflows/manifests.yaml@beta

  # Deployment:
  #   name: Deployment
  #   needs: [BuildMaven, BuildManifests]
  #   uses: KTijssen/global-actions/.github/workflows/deployment.yaml@beta