name: project-a

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      run_e2e_test:
        description: Run E2E tests
        required: true
        type: boolean
        default: false

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  checkout:
    name: Checkout Project Repo
    runs-on: [self-hosted]
    steps:       
      - name: Checkout project repository
        uses: actions/checkout@v3

  setVersion:
    needs: checkout
    name: Common
    uses: KTijssen/global-actions/.github/workflows/common.yaml@beta
    secrets: inherit
    with:
      major: "1"
      minor: "0"

  buildMaven:
    name: Build
    needs: setVersion
    uses: KTijssen/global-actions/.github/workflows/build_maven.yaml@beta
    secrets: inherit
    with:
      gitTag: ${{ needs.SetVersion.outputs.gitTag }}

  buildManifests:
    name: Build
    needs: setVersion
    uses: KTijssen/global-actions/.github/workflows/build_manifests.yaml@beta
    with:
      gitTag: ${{ needs.SetVersion.outputs.gitTag }}

  kubernetes:
    name: Kubernetes
    needs: [buildMaven, buildManifests]
    uses: KTijssen/global-actions/.github/workflows/kubernetes.yaml@beta